
package Controller;


public enum EnumDepartament {
    SeleccionaOpcion,
    Amazonas,
    Antioquia,
    Arauca,
    Atlántico,
    Bogotá,
    Bolívar,
    Boyacá,
    Caldas,
    Caquetá,
    Casanare,
    Cauca,
    Cesar,
    Chocó,
    Córdoba,
    Cundinamarca,
    Guainía,
    Guaviare,
    Huila,
    LaGuajira,
    Magdalena,
    Meta,
    Nariño,
    NortedeSantander,
    Putumayo,
    Quindío,
    Risaralda,
    SanAndrésyProvidencia,
    Santander,
    Sucre,
    Tolima,
    ValledelCauca,
    Vaupés,
    Vichada
}
